test:
  iteration: -1
  loss: -1
  match_loss: -1
  non_match_loss: -1
train:
  background_non_match_loss: -1
  blind_non_match_loss: -1
  different_object_non_match_loss: -1
  iteration: -1
  learning_rate: 1.2157665459056937e-05
  loss: -1
  masked_non_match_loss: -1
  match_loss: -1
  total_loss: 8.160039601926865
